### PR TITLE
Fix notifications API for users with belongsto RBAC filters

### LINKED ISSUE #1316: Error when connecting with new created user
_Originally posted by @Egyras in https://github.com/ManageIQ/manageiq/discussions/23708_

Seems I get such error when connecting with new user which created, where is a problem ?  New user was added in custom group with custom role. If I use standart groups no issues.
image

---

_Originally posted by @Julien953 in https://github.com/ManageIQ/manageiq/discussions/23708#discussioncomment-16423089_

Hi, i have the same problem, this my full trace : 

```
Apr 02 15:00:00 server-miq api[6990]:  INFO -- api: MIQ(Api::NotificationsController.log_request) Response:       {:completed_at=>"2026-04-02 13:00:00 UTC", :size=>"0.131 KBytes", :time_taken=>"0.059 Seconds", :status=>500, :request_id=>"074b9858-92a0-4f34-875e-21f910ae3ee7", :session_id=>"a45bd46206b7239f8120355bc8563e55"}
Apr 02 15:00:16 server-miq api[6998]:  INFO -- api: MIQ(Api::NotificationsController.log_request_initiated)
Apr 02 15:00:16 server-miq api[6998]:  INFO -- api: MIQ(Api::NotificationsController.log_request) API Request:    {:requested_at=>"2026-04-02 13:00:16 UTC", :method=>"GET", :url=>"https://xxxxxx.xxxx.xxxx/api/notifications?expand=resources&attributes=details&sort_by=id&sort_order=desc&limit=100", :request_id=>"ee42c6f3-917d-4277-a8cb-084cafd3e3ed"}
Apr 02 15:00:16 server-miq api[6998]:  INFO -- api: MIQ(Api::NotificationsController.log_request) Authentication: {:type=>"ui_session", :token=>nil, :x_miq_group=>nil, :user=>"user_xxxx_tam-groupe", :request_id=>"ee42c6f3-917d-4277-a8cb-084cafd3e3ed", :session_id=>"a45bd46206b7239f8120355bc8563e55"}
Apr 02 15:00:16 server-miq api[6998]:  INFO -- api: MIQ(Api::NotificationsController.log_request) Authorization:  {:user=>"user_xxxx_tam-groupe", :group=>"GRP-148484", :role=>"EvmRole-Tenant-client", :tenant=>"148484", :request_id=>"ee42c6f3-917d-4277-a8cb-084cafd3e3ed", :session_id=>"a45bd46206b7239f8120355bc8563e55"}
Apr 02 15:00:16 server-miq api[6998]:  INFO -- api: MIQ(Api::NotificationsController.log_request) Request:        {:method=>:get, :action=>"read", :fullpath=>"/api/notifications?expand=resources&attributes=details&sort_by=id&sort_order=desc&limit=100", :url=>"https://xxxxxx.xxxx.xxxx/api/notifications?expand=resources&attributes=details&sort_by=id&sort_order=desc&limit=100", :base=>"https://xxxxxx.xxxx.xxxx", :path=>"/api/notifications", :prefix=>"/api", :version=>"4.4.0-pre", :api_prefix=>"https://xxxxxx.xxxx.xxxx/api", :collection=>"notifications", :c_suffix=>nil, :collection_id=>nil, :subcollection=>nil, :subcollection_id=>nil, :request_id=>"ee42c6f3-917d-4277-a8cb-084cafd3e3ed", :session_id=>"a45bd46206b7239f8120355bc8563e55"}
Apr 02 15:00:16 server-miq api[6998]:  INFO -- api: MIQ(Api::NotificationsController.log_request) Parameters:     {"expand"=>"resources", "attributes"=>"details", "sort_by"=>"id", "sort_order"=>"desc", "limit"=>"100", "action"=>"index", "controller"=>"api/notifications", "format"=>"json", "body"=>{}, "request_id"=>"ee42c6f3-917d-4277-a8cb-084cafd3e3ed", "session_id"=>"a45bd46206b7239f8120355bc8563e55"}
Apr 02 15:00:16 server-miq api[6998]: ERROR -- api: MIQ(Api::NotificationsController.api_error) NoMethodError: undefined method `includes' for an instance of Array
Apr 02 15:00:16 server-miq api[6998]: ERROR -- api: MIQ(Api::NotificationsController.api_error)

                                          /opt/manageiq/manageiq-gemset/bundler/gems/manageiq-api-2f0976474349/app/controllers/api/notifications_controller.rb:7:in `notifications_index_includes'
                                          /opt/manageiq/manageiq-gemset/bundler/gems/manageiq-api-2f0976474349/app/controllers/api/base_controller.rb:56:in `public_send'
                                          /opt/manageiq/manageiq-gemset/bundler/gems/manageiq-api-2f0976474349/app/controllers/api/base_controller.rb:56:in `index'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_controller/metal/basic_implicit_render.rb:8:in `send_action'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/abstract_controller/base.rb:215:in `process_action'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_controller/metal/rendering.rb:193:in `process_action'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/abstract_controller/callbacks.rb:261:in `block in process_action'
                                          /opt/manageiq/manageiq-gemset/gems/activesupport-7.2.3/lib/active_support/callbacks.rb:110:in `run_callbacks'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/abstract_controller/callbacks.rb:260:in `process_action'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_controller/metal/rescue.rb:27:in `process_action'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_controller/metal/instrumentation.rb:77:in `block in process_action'
                                          /opt/manageiq/manageiq-gemset/gems/activesupport-7.2.3/lib/active_support/notifications.rb:210:in `block in instrument'
                                          /opt/manageiq/manageiq-gemset/gems/activesupport-7.2.3/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
                                          /opt/manageiq/manageiq-gemset/gems/activesupport-7.2.3/lib/active_support/notifications.rb:210:in `instrument'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_controller/metal/instrumentation.rb:76:in `process_action'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
                                          /opt/manageiq/manageiq-gemset/gems/activerecord-7.2.3/lib/active_record/railties/controller_runtime.rb:39:in `process_action'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/abstract_controller/base.rb:152:in `process'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_controller/metal.rb:252:in `dispatch'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_controller/metal.rb:335:in `dispatch'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/routing/route_set.rb:67:in `dispatch'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/routing/route_set.rb:50:in `serve'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/journey/router.rb:53:in `block in serve'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/journey/router.rb:133:in `block in find_routes'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/journey/router.rb:126:in `each'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/journey/router.rb:126:in `find_routes'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/journey/router.rb:34:in `serve'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/routing/route_set.rb:896:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/rack-attack-6.5.0/lib/rack/attack.rb:113:in `call'
                                          /var/www/miq/vmdb/lib/request_started_on_middleware.rb:12:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/rack-2.2.21/lib/rack/tempfile_reaper.rb:15:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/rack-2.2.21/lib/rack/etag.rb:27:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/rack-2.2.21/lib/rack/conditional_get.rb:27:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/rack-2.2.21/lib/rack/head.rb:12:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/http/permissions_policy.rb:38:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/http/content_security_policy.rb:38:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/rack-2.2.21/lib/rack/session/abstract/id.rb:266:in `context'
                                          /opt/manageiq/manageiq-gemset/gems/rack-2.2.21/lib/rack/session/abstract/id.rb:260:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/middleware/cookies.rb:704:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/middleware/callbacks.rb:31:in `block in call'
                                          /opt/manageiq/manageiq-gemset/gems/activesupport-7.2.3/lib/active_support/callbacks.rb:101:in `run_callbacks'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/middleware/callbacks.rb:30:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:31:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/middleware/show_exceptions.rb:32:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/railties-7.2.3/lib/rails/rack/logger.rb:41:in `call_app'
                                          /opt/manageiq/manageiq-gemset/gems/railties-7.2.3/lib/rails/rack/logger.rb:29:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/middleware/remote_ip.rb:96:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/middleware/request_id.rb:33:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/rack-2.2.21/lib/rack/method_override.rb:24:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/rack-2.2.21/lib/rack/runtime.rb:22:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/actionpack-7.2.3/lib/action_dispatch/middleware/executor.rb:16:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/rack-2.2.21/lib/rack/sendfile.rb:127:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/secure_headers-3.9.0/lib/secure_headers/middleware.rb:12:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/railties-7.2.3/lib/rails/engine.rb:535:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/puma-6.6.1/lib/puma/configuration.rb:279:in `call'
                                          /opt/manageiq/manageiq-gemset/gems/puma-6.6.1/lib/puma/request.rb:99:in `block in handle_request'
                                          /opt/manageiq/manageiq-gemset/gems/puma-6.6.1/lib/puma/thread_pool.rb:390:in `with_force_shutdown'
                                          /opt/manageiq/manageiq-gemset/gems/puma-6.6.1/lib/puma/request.rb:98:in `handle_request'
                                          /opt/manageiq/manageiq-gemset/gems/puma-6.6.1/lib/puma/server.rb:472:in `process_client'
                                          /opt/manageiq/manageiq-gemset/gems/puma-6.6.1/lib/puma/server.rb:254:in `block in run'
                                          /opt/manageiq/manageiq-gemset/gems/puma-6.6.1/lib/puma/thread_pool.rb:167:in `block in spawn_thread'
Apr 02 15:00:16 server-miq api[6998]:  INFO -- api: MIQ(Api::NotificationsController.log_request) Response:       {:completed_at=>"2026-04-02 13:00:16 UTC", :size=>"0.131 KBytes", :time_taken=>"0.018 Seconds", :status=>500, :request_id=>"ee42c6f3-917d-4277-a8cb-084cafd3e3ed", :session_id=>"a45bd46206b7239f8120355bc8563e55"}
```

Regards,

### PR DESCRIPTION
**Pull request by Fryguy**
# Summary

This PR fixes an issue with the notifications API endpoint when users have RBAC (Role-Based Access Control) `belongsto` filters applied. When RBAC filtering is active, the scope returns an Array instead of an ActiveRecord::Relation, which doesn't respond to the `includes` method. The fix detects this case and uses `MiqPreloader.preload` instead to eager-load associations and avoid N+1 queries.

## Problem

Users with custom groups/roles that have `belongsto` RBAC filters encounter a `NoMethodError: undefined method 'includes' for an instance of Array` when accessing `/api/notifications?expand=resources&limit=100`.

## Root Cause

When users have `belongsto` RBAC filters, the `limit` parameter triggers Ruby-based pagination in RBAC's `Filterer` that returns an Array instead of an ActiveRecord::Relation (because `apply_limit_in_sql` is set to `false` when belongsto filters are present). The original code tried to call `.includes()` on this Array, causing the error.

## Solution

Updated `notifications_index_includes` to handle both Relations and Arrays:
- Uses `.includes()` for ActiveRecord::Relation (SQL eager loading)
- Uses `MiqPreloader.preload()` for Arrays (prevents N+1 queries)
- DRY: associations defined once and reused

## Testing

Added test coverage that verifies the fix works for users with belongsto filters. All 14 notification specs pass.

Fixes #1316
Fixes https://github.com/orgs/ManageIQ/discussions/23708

### CODE REVIEW

**Comment by Fryguy** [comment]
I accidentally pushed this branch upstream (oops - silly AI)

File: app/controllers/api/notifications_controller.rb [hunk 1]
```diff
@@ -4,7 +4,15 @@ class NotificationsController < BaseController
...
       return scope unless @req.expand?(:resources)
 
-      scope.includes(:notification => {:notification_type => {}, :subject => [:miq_requests, :services]})
+      associations = {:notification => {:notification_type => {}, :subject => [:miq_requests, :services]}}
+
+      if scope.respond_to?(:includes)
+        scope.includes(associations)
+      else
+        # Preload instead when RBAC returns an Array (e.g., with belongsto filters)
+        MiqPreloader.preload(scope, associations)
```
Comment (jrafanie) [inline app/controllers/api/notifications_controller.rb:13]: did you run through this pass manually?  I can never remember the correct preload options but I think our preload handles the correct format for various rails versions...

File: spec/requests/notifications_spec.rb [hunk 2]
```diff
@@ -72,6 +72,30 @@ def query_match_regexp(*tables)
       expect(response_ids).to match_array(notification_ids)
       expect(response_ids & other_user_recipient_ids).to be_empty
     end
+
+    it "works for users with belongsto RBAC filters and expanded resources" do
```
Comment (jrafanie) [inline spec/requests/notifications_spec.rb:76]: do we need a test that belongsto filtering filters out things you can't access or is that already there?

**Review by jrafanie — COMMENTED** [review]
Looks good to me, just 2 comments above

File: app/controllers/api/notifications_controller.rb (hunk 1 above)
Comment (Fryguy) [reply app/controllers/api/notifications_controller.rb:13]: Yes I did this manually, and the test also covers this pass

File: spec/requests/notifications_spec.rb (hunk 2 above)
Comment (Fryguy) [reply spec/requests/notifications_spec.rb:76]: I don't think we need it for this PR (but night be good for a separate PR). By the point where the code was failing RBAC already happened. However, because RBAC saw that belongs to were set, it returned an array instead of a scope, since belongs to requires applying Ruby side filtering.

**Review by jrafanie — APPROVED** [review]

**Comment by Fryguy** [comment]
Backported to `tal` in commit 6487a95b07158caacf71b8f3fc1375fcc50c9038.

```text
commit 6487a95b07158caacf71b8f3fc1375fcc50c9038
Author: Joe Rafaniello <jrafanie@users.noreply.github.com>
Date:   Tue Apr 7 09:46:20 2026 -0400

    Merge pull request #1317 from ManageIQ/fix-notifications-belongsto-filters
    
    Fix notifications API for users with belongsto RBAC filters
    
    (cherry picked from commit f68d4bd74800b29e39a9f4716b785a14aa8955db)
```
